// 游戏数据配置
const gamesConfig = {
    games: [
        {
            "id": 1744360201816,
            "title": "Hazmob FPS: Online Shooter",
            "shortDescription": "Hazmob FPS: Online Shooter is a multiplayer shooting FPS game where every second counts! Play against other players across multiple game modes in non-stop combat. This first-person shooter game is ideal for those seeking a bit of thrill.",
            "fullDescription": "Skilled FPS players will love Hazmob FPS: Online Shooter. The game features excellent, clean 3D graphics with a fluid and intuitive control system that allows you to maneuver quickly and tactically. The maps are designed for fast-paced battles in a close-quarters setting, leaving it down to pure reflex and skill to get the job done.\n\nUpgrade your weapons\n\nThe weapon collection is extensive, with 55+ customizable weapons in the SMG, assault, shotgun, sniper, and LMG categories. The game features excellent progression that allows you to unlock new weapons and attachments as you level up. You can fit scopes, skins, and keychains and upgrade the abilities of each gun you own.\n\nEarn more money for gear\n\nAlong with the weapons, you can also equip clothing items to improve your base character stats. To get access to these additional items, you also need to buy them using the currency you earn from battles. Complete daily and weekly missions to earn even more money to put toward your new gear.\n\nCreate custom matches\n\nWith the ability to create a custom game, you can also play private matches against friends or more competitive fights against rival clans. The competitive rank system keeps track of the best clans, showing the trophies and XP scores to add an extra element of competition.\n\nPlay various game modes\n\nWant to jump right into the action? Click quick battle and play a random game on one of the eight available maps. You can also play a range of other game modes; these are:\n\nTeam Deathmatch\nSearch and Destroy\nCapture the flag\nDomination\nFree for all\nElimination\nGun race",
            "imageUrl": "https://imgs.crazygames.com/hazmob-fps-online-shooter_16x9/20240607181337/hazmob-fps-online-shooter_16x9-cover?metadata=none&quality=70&width=475",
            "category": "shooting",
            "rating": 4.2,
            "playCount": 7438,
            "releaseDate": "2025-04-11",
            "iframeUrl": "https://www.crazygames.com/embed/hazmob-fps-online-shooter"
          },
          {
            "id": 1744365923163,
            "title": "Racing Limits",
            "shortDescription": "Racing Limits is a racing game that lets you push your skills to the max. Race and overtake vehicles in city and highway traffic with four thrilling game modes: carrier, infinite, against-time, and free mode. Choose between one-way and two-way traffic, and experience three times of day - 'Morning,' 'Sunset,' and 'Night.' With multiple camera angles, sensitive controls, and realistic physics, it's a high-speed adventure you won't want to miss. Customize, upgrade, and take on numerous race events in this graphically stunning racing world!\n",
            "fullDescription": "Controls\nUp arrow key to accelerate\nDown arrow key to decelerate\nLeft and right arrow keys to steer\nC to change the camera view\nF to use nitro\nE to horn\nW to gear up in manual gear mode\nD to gear down in manual gear mode\nESC to quit current progress",
            "imageUrl": "https://imgs.crazygames.com/racing-limits_16x9/20231106035424/racing-limits_16x9-cover?metadata=none&quality=70&width=475",
            "category": "crazycar",
            "rating": 4.4,
            "playCount": 1895,
            "releaseDate": "2025-04-11",
            "iframeUrl": "https://www.crazygames.com/embed/racing-limits"
          },
          {
            "id": 1744446997526,
            "title": "BuildNow GG",
            "shortDescription": "BuildNow GG is an online build-and-shoot game featuring various game modes, weapons, and maps. Build and battle your way to the top of the leaderboard and hone your skills in offline training mode.",
            "fullDescription": "Movement\nWASD or arrow keys = move\nSpace = jump\nBuilding\nQ = wall\nC = floor\nV = ramp\nLeft shift = roof\nF = edit\nF = apply edit\nRight-click = reset edit\nScroll wheel down = fast edit reset\nWeapon\nLeft-click = fire\nRight-click = aim\nZ = pickax\n1 = slot 1\n2 = slot 2\n3 = slot 3\n4 = slot 4\n5 = slot 5\nOthers\nB = emotes\nP = open chat\nM = scoreboard",
            "imageUrl": "https://imgs.crazygames.com/buildnow-gg_16x9/20250217093036/buildnow-gg_16x9-cover?metadata=none&quality=70&width=295",
            "category": "board",
            "rating": 4.5,
            "playCount": 6667,
            "releaseDate": "2025-04-12",
            "iframeUrl": "https://www.crazygames.com/embed/buildnow-gg"
          },
          {
            "id": 1744449850481,
            "title": "Stickman Destruction 3 Heroes",
            "shortDescription": "Stickman Destruction 3 Heroes is a ragdoll physics action game. Crash the stickman into obstacles, send him tumbling down staircases and through walls into oblivious bystanders. Cause as much destruction as possible to earn the most gold!",
            "fullDescription": "Left mouse button",
            "imageUrl": "https://imgs.crazygames.com/stickman-destruction-3-heroes/20210311140018/stickman-destruction-3-heroes-cover?metadata=none&quality=70&width=475",
            "category": "action",
            "rating": 4.1,
            "playCount": 4205,
            "releaseDate": "2025-04-12",
            "iframeUrl": "https://www.crazygames.com/embed/stickman-destruction-3-heroes"
          },
          {
            "id": 1744449914416,
            "title": "Traffic Rider",
            "shortDescription": "Traffic Rider is a first-person driving bike endless game that puts you on a motorbike for an exhilarating ride. With a full career mode, lifelike bike sounds, and detailed graphics, it redefines arcade racing. Speed through highways, overtake traffic, and upgrade your rides to conquer challenging missions. Embrace the thrill and master the art of smooth racing.",
            "fullDescription": "Up arrow = throttle\nDown arrow = brake\nLeft arrow = left\nRight arrow = right\nHorn = H\nWheelie = Y\nLook left = T\nLook right = U\nGear up = R\nGear down = F\nPause = P or F1\nYou can always change controls in settings menu.",
            "imageUrl": "https://imgs.crazygames.com/traffic-rider-vvq_16x9/20250328101418/traffic-rider-vvq_16x9-cover?metadata=none&quality=70&width=475",
            "category": "racing",
            "rating": 4.4,
            "playCount": 8927,
            "releaseDate": "2025-04-12",
            "iframeUrl": "https://www.crazygames.com/embed/traffic-rider-vvq"
          },
          {
            "id": 1744449980820,
            "title": "MX Offroad Master",
            "shortDescription": "MX Offroad Master is a driving bike game where you cycle down steep mountain slopes. Hop on any of the four mountain bikes and get ready for high-octane stunts. You can play either free ride or mountain ride game modes, and there is the option to play locally with a friend or solo.",
            "fullDescription": "Player 1\nWASD = move\nSpace = front brake\nS = rear brake\nC = camera switch\nR = restart position\nPlayer 2\nArrow keys = move\nR-shift = front brake\nDown arrow key = rear brake\nO= camera switch\nP = restart position",
            "imageUrl": "https://imgs.crazygames.com/mx-offroad-master/20230206090722/mx-offroad-master-cover?metadata=none&quality=70&width=475",
            "category": "bike",
            "rating": 4.1,
            "playCount": 3898,
            "releaseDate": "2025-04-12",
            "iframeUrl": "https://www.crazygames.com/embed/mx-offroad-master"
          },
          {
            "id": 1744450099618,
            "title": "Basketball Superstars",
            "shortDescription": "Basketball Superstars is a dynamic basketball experience where you create and train your ultimate player. Customize your gear, enhance your skills, and face intense rivals in fast-paced matches. Whether you are outsmarting opponents or perfecting your strategy, each game delivers action and excitement as you strive to dominate the court and showcase your prowess.",
            "fullDescription": "Controls\nMove = Use the Arrow Keys to dribble and navigate around the court.\nShoot = Press and hold the Spacebar, then release it at just the right moment to score.\nDunk = Get close to the hoop and press the Spacebar to slam it home with style!\nSteal = Get close to your opponent and tap the Spacebar to steal the ball.\nBlock = Tap the Spacebar at just the right time to block your opponent's shot.",
            "imageUrl": "https://imgs.crazygames.com/basketball-superstars_16x9/20250117063641/basketball-superstars_16x9-cover?metadata=none&quality=70&width=475",
            "category": "action",
            "rating": 4.2,
            "playCount": 8185,
            "releaseDate": "2025-04-12",
            "iframeUrl": "https://www.crazygames.com/embed/basketball-superstars"
          },
          {
            "id": 1744451034002,
            "title": "Master Chess",
            "shortDescription": "Master Chess is an online casual chess game with single and multiplayer options. If you want to show off your chess skills, try out this digital tabletop online browser version. In this title, you can play three different game modes and test your skills against other chess players.",
            "fullDescription": "Use the left mouse button to select a unit and move it.",
            "imageUrl": "https://imgs.crazygames.com/games/master-chess/cover-1624894080822.png?metadata=none&quality=70&width=475",
            "category": "chess",
            "rating": 4.2,
            "playCount": 3498,
            "releaseDate": "2025-04-12",
            "iframeUrl": "https://www.crazygames.com/embed/master-chess"
          },
          {
            "id": 1744451103241,
            "title": "Teacher Simulator",
            "shortDescription": "Teacher Simulator is a fun simulation game in which you play the role of a teacher. Mark exams and ensure the kids are on their best behavior. You may have been the student, but now you get to be the one in charge!",
            "fullDescription": "Use the left mouse button to play the game.",
            "imageUrl": "https://imgs.crazygames.com/teacher-simulator/20220907173822/teacher-simulator-cover?metadata=none&quality=70&width=475",
            "category": "simulation",
            "rating": 4.1,
            "playCount": 829,
            "releaseDate": "2025-04-12",
            "iframeUrl": "https://www.crazygames.com/embed/teacher-simulator"
          },
          {
            "id": 1744451157333,
            "title": "8 Ball Billiards Classic",
            "shortDescription": "8-Ball Billiards is a free online pool game in our sports category ideal for one or two players. You can play solo against AI or challenge other players in two-player mode. The game is easy for anyone to play, so pick up a cue and line up your first shot.",
            "fullDescription": "Move your mouse to aim\nDrag the left mouse button backward to set power and release it to shoot",
            "imageUrl": "https://imgs.crazygames.com/8-ball-billiards-classic_16x9/20231108025958/8-ball-billiards-classic_16x9-cover?metadata=none&quality=70&width=475",
            "category": "arcade",
            "rating": 4.6,
            "playCount": 8041,
            "releaseDate": "2025-04-12",
            "iframeUrl": "https://www.crazygames.com/embed/8-ball-billiards-classic"
          },
          {
            "id": 1744451215477,
            "title": "Murder Mafia",
            "shortDescription": "Murder Mafia is a fun, one-button casual game that will keep you entertained for hours. Your mission? Take down the notorious mafia boss, the Don—but beware of sneaky traitors lurking in the shadows! Explore unpredictable scenarios and unlock them all as you hone your skills in the art of deception. Sometimes, you are deceiving, but most of the time, you will be deceived. Can you outsmart the mafia and rise to the top?",
            "fullDescription": "Use the left mouse button to play the game.",
            "imageUrl": "https://imgs.crazygames.com/murder-mafia_16x9/20230915113149/murder-mafia_16x9-cover?metadata=none&quality=70&width=475",
            "category": "adventure",
            "rating": 4.6,
            "playCount": 4090,
            "releaseDate": "2025-04-12",
            "iframeUrl": "https://www.crazygames.com/embed/murder-mafia"
          },
          {
            "id": 1744451268850,
            "title": "Modern Cannon Strike",
            "shortDescription": "Modern Cannon Strike is an action game in which you must launch a missile to destroy your enemy. Aim at the specific location, and then fire! You can easily aim for your enemies by looking at the red target on the tablet and then timing your shots. Enjoy the game, and get ready for the battle!",
            "fullDescription": "PC Controls\nDrag the left mouse button to aim and release to shoot.",
            "imageUrl": "https://imgs.crazygames.com/modern-cannon-strike_16x9/20240409071436/modern-cannon-strike_16x9-cover?metadata=none&quality=70&width=475",
            "category": "action",
            "rating": 4.4,
            "playCount": 4338,
            "releaseDate": "2025-04-12",
            "iframeUrl": "https://www.crazygames.com/embed/modern-cannon-strike"
          },
          {
            "id": 1744451327258,
            "title": "CG FC 25",
            "shortDescription": "CG FC 25 is a dynamic soccer simulation game that lets you lead your favorite teams to victory. With intuitive joystick controls, sprint and kick features, and realistic 3D stadiums, you'll immerse yourself in intense matches. Choose from Quick Match or Tournament modes, customize your player, and experience the thrill of football in a vibrant, HD arena.",
            "fullDescription": "Controls\nWASD or arrow keys = move\nX or mouse left key = kick\nZ or mouse right click = pass\nLeft shift or right shift = sprint\nSpace = jump\nC = crouch\nMouse = swipe and navigate with onscreen buttons",
            "imageUrl": "https://imgs.crazygames.com/games/cg-fc-24/cover_16x9-1734927491009.png?metadata=none&quality=70&width=475",
            "category": "simulation",
            "rating": 4.7,
            "playCount": 9814,
            "releaseDate": "2025-04-12",
            "iframeUrl": "https://www.crazygames.com/embed/cg-fc-24"
          },
          {
            "id": 1744468847147,
            "title": "Doors Castle",
            "shortDescription": "Doors Castle is a thrilling adventure through a haunted fortress filled with secrets, puzzles, and lurking horrors. Every shadow hides danger, every door holds a mystery. Explore eerie hallways, uncover hidden paths, and stay one step ahead of the creatures stalking the dark.\n\n",
            "fullDescription": "Controls\nWASD = move\nE = interact with an object (open door, pick up keys)\nC = crouch\nX = drop selected item\nTab = cursor ON / OFF (with the cursor on, the control is disabled)\nO = open settings menu\nT = open chat",
            "imageUrl": "https://imgs.crazygames.com/doors-castle_16x9/20250408044736/doors-castle_16x9-cover?metadata=none&quality=70&width=475",
            "category": "escape",
            "rating": 4.9,
            "playCount": 269,
            "releaseDate": "2025-04-12",
            "iframeUrl": "https://www.crazygames.com/embed/doors-castle"
          },
          {
            "id": 1744699275951,
            "title": "Foono Online Multiplayer",
            "shortDescription": "Foono Online Multiplayer is an engaging card game that takes inspiration from classics like Uno Online and Crazy Eights. The objective is to clear your hand of cards before your opponents do. It's a game of strategy, quick thinking, and a bit of luck. Foono offers endless fun and opportunities for social interaction. Whether you're playing casually with friends or in competitive online matches, Foono promises an entertaining card game experience!",
            "fullDescription": "Controls\nUse the left mouse button to click or select a card when it's your turn, or the side card to draw a card.",
            "imageUrl": "https://imgs.crazygames.com/foono-online-multiplayer-card-game_16x9/20231002101605/foono-online-multiplayer-card-game_16x9-cover?metadata=none&quality=70&width=475",
            "category": "action",
            "rating": 4.5,
            "playCount": 7197,
            "releaseDate": "2025-04-15",
            "iframeUrl": "https://www.crazygames.com/embed/foono-online-multiplayer-card-game"
          },
          {
            "id": 1744699367552,
            "title": "Nébula Tarot Cat",
            "shortDescription": "Nébula Tarot Cat is a mystical journey where you consult a magical AI-powered cat for guidance. Dive into the enchanting world of tarot, ask your burning questions, and uncover the universe’s secrets through Nébula’s intuitive wisdom. With every card drawn, her insights illuminate your path, blending esoteric charm and AI precision to reveal the answers you seek.",
            "fullDescription": "Controls\nUse the left mouse button to play.",
            "imageUrl": "https://imgs.crazygames.com/nebula-tarot-cat-uee_16x9/20250214041139/nebula-tarot-cat-uee_16x9-cover?metadata=none&quality=70&width=475",
            "category": "card",
            "rating": 4.1,
            "playCount": 4432,
            "releaseDate": "2025-04-15",
            "iframeUrl": "https://www.crazygames.com/embed/nebula-tarot-cat-uee"
          },
          {
            "id": 1744699417918,
            "title": "Dungeon of Terror",
            "shortDescription": "Dungeon of Terror is a thrilling casual deck-building game where strategy, resource management, and survival come together. Your mission is to navigate a labyrinthine dungeon, gather resources, and release imprisoned captives—all while avoiding the wrath of the terrifying Minotaur that lurks within.",
            "fullDescription": "Controls\nDrag and drop the card onto the dungeon to use it\nLeft mouse button to zoom and interact with in-game UI\nDouble LMB to move to an adjacent room\nHold RMB to show the room details",
            "imageUrl": "https://imgs.crazygames.com/dungeon-of-terror_16x9/20241223042103/dungeon-of-terror_16x9-cover?metadata=none&quality=70&width=475",
            "category": "simulation",
            "rating": 4.8,
            "playCount": 3099,
            "releaseDate": "2025-04-15",
            "iframeUrl": "https://www.crazygames.com/embed/dungeon-of-terror"
          },
          {
            "id": 1744699474982,
            "title": "Robox",
            "shortDescription": "Robox is a puzzle platformer game where you control a robot to find the exit door. Help him to escape enemies and traps along the way. Jump, shoot the boxes using your teleportation gun, and try to reach the door. Good luck!\n\n",
            "fullDescription": "Controls\nA / left arrow key = move left\nD / right arrow key = move right\nW / Z = jump\nE / J = shoot\nR = reset\nEsc / B = back",
            "imageUrl": "https://imgs.crazygames.com/robox_16x9/20250414091125/robox_16x9-cover?metadata=none&quality=70&width=475",
            "category": "shooter",
            "rating": 4.3,
            "playCount": 8540,
            "releaseDate": "2025-04-15",
            "iframeUrl": "https://www.crazygames.com/embed/robox"
          },
          {
            "id": 1744699615488,
            "title": "Street Fighter Simulator",
            "shortDescription": "Street Fighter Simulator is an action-packed fighting game where you rise through the ranks by mastering your combat skills, unlocking new abilities, and battling fierce opponents in dynamic and immersive environments. Whether you’re in Arcade Mode enjoying custom battles or in Career Mode earning your place as a champion, every fight brings you closer to becoming the Ultimate Street Fighter.\n\n",
            "fullDescription": "Controls\nWASD = move\nUp arrow key = block\nDown arrow key = kick\nLeft arrow key = punch\nWASD + right arrow key = dodge\nTab = paus",
            "imageUrl": "https://imgs.crazygames.com/street-fighter-simulator_16x9/20250210050647/street-fighter-simulator_16x9-cover?metadata=none&quality=70&width=475",
            "category": "action",
            "rating": 4.2,
            "playCount": 434,
            "releaseDate": "2025-04-15",
            "iframeUrl": "https://www.crazygames.com/embed/street-fighter-simulator"
          },
          {
            "id": 1744700756630,
            "title": "Medieval Arena",
            "shortDescription": "Medieval Arena is a thrilling multiplayer combat game set in a blocky, immersive battlefield. Choose your path as an Archer, Swordsman, or Berserker, and dive into intense PvP matches. Sharpen your tactics, hone your skills, and outwit opponents in fast-paced action. Perfect for those seeking medieval warfare and heart-pounding competition. Claim victory and rise above the rest!\n\n",
            "fullDescription": "Controls\nWASD to move\nSpace to jump\nLeft mouse to fire/attack\nTab to open stats and settings",
            "imageUrl": "https://imgs.crazygames.com/medieval-arena_16x9/20250411173533/medieval-arena_16x9-cover?metadata=none&quality=70&width=475",
            "category": "action",
            "rating": 4.5,
            "playCount": 9983,
            "releaseDate": "2025-04-15",
            "iframeUrl": "https://www.crazygames.com/embed/medieval-arena"
          },
          {
            "id": 1744700809184,
            "title": "Hyperspace: Quantum Fracture",
            "shortDescription": "Hyperspace: Quantum Fracture is a sci-fi shoot 'em up blending roguelike progression, bullet hell intensity, and auto-shooter action. You are on a thrilling journey through deep space, facing relentless enemy swarms. Test your survival skills in the vast unknown.\n\n",
            "fullDescription": "PC Controls\nUse WASD / arrow keys /drag the left mouse button to move.\n\nMobile Controls\nDrag in the direction you want to go.",
            "imageUrl": "https://imgs.crazygames.com/hyperspace---quantum-fracture-fez_16x9/20250402083340/hyperspace---quantum-fracture-fez_16x9-cover?metadata=none&quality=70&width=475",
            "category": "shooter",
            "rating": 4.8,
            "playCount": 8605,
            "releaseDate": "2025-04-15",
            "iframeUrl": "https://www.crazygames.com/embed/hyperspace---quantum-fracture-fez"
          },
          {
            "id": 1744700865525,
            "title": "Blitzkrieg Assault: War Zone!",
            "shortDescription": "Blitzkrieg Assault: War Zone is an intense shooter with tower defense elements set in the chaos of World War II. Take on the unstoppable armored train, using only your machine gun and sharp aim to halt its advance. Destroy train cars, upgrade skill cards, and master strategic combat in a fast-paced battle for victory.\n\n",
            "fullDescription": "Controls\nUse the left mouse button / WASD / arrow keys to aim and shoot.",
            "imageUrl": "https://imgs.crazygames.com/blitzkrieg-assault-war-zone_16x9/20250331074441/blitzkrieg-assault-war-zone_16x9-cover?metadata=none&quality=70&width=475",
            "category": "shooter",
            "rating": 4.4,
            "playCount": 1024,
            "releaseDate": "2025-04-15",
            "iframeUrl": "https://www.crazygames.com/embed/blitzkrieg-assault-war-zone"
          },
          {
            "id": 1744700935526,
            "title": "Modern Cannon Strike",
            "shortDescription": "Modern Cannon Strike is an action game in which you must launch a missile to destroy your enemy. Aim at the specific location, and then fire! You can easily aim for your enemies by looking at the red target on the tablet and then timing your shots. Enjoy the game, and get ready for the battle!\n\n",
            "fullDescription": "Controls\nPC Controls\nDrag the left mouse button to aim and release to shoot.\n\nMobile Controls\nDrag with your finger to aim and release to shoot.",
            "imageUrl": "https://imgs.crazygames.com/modern-cannon-strike_16x9/20240409071436/modern-cannon-strike_16x9-cover?metadata=none&quality=70&width=475",
            "category": "action",
            "rating": 4.5,
            "playCount": 5310,
            "releaseDate": "2025-04-15",
            "iframeUrl": "https://www.crazygames.com/embed/modern-cannon-strike"
          },
          {
            "id": 1744701035310,
            "title": "Right Jump",
            "shortDescription": "Right Jump is an exciting casual platformer game that tests your agility and strategy! In Right Jump, timing is everything—jump at the perfect moment to navigate through tricky platforms, elevators, trampolines, and moving obstacles. Can you reach the end of each level?\n\n",
            "fullDescription": "Controls\nHold the left mouse button to aim your move and release it to jump, or use the AD or arrow keys to perform the move and release to jump",
            "imageUrl": "https://imgs.crazygames.com/right-jump_16x9/20250402075906/right-jump_16x9-cover?metadata=none&quality=70&width=475",
            "category": "strategy",
            "rating": 4.7,
            "playCount": 5122,
            "releaseDate": "2025-04-15",
            "iframeUrl": "https://www.crazygames.com/embed/right-jump"
          },
          {
            "id": 1744701076142,
            "title": "Bicycle Kick Champ",
            "shortDescription": "Bicycle Kick Champ is an arcade game where you have one purpose - bicycle kick the ball into the goal! Time your shots perfectly to make sure they aren't blocked and aim to get the highest score as you keep hitting those passes into the net.\n\n",
            "fullDescription": "Controls\nLeft-click = shoot",
            "imageUrl": "https://imgs.crazygames.com/games/bicycle-kick-champ/cover-1630293242636.png?metadata=none&quality=70&width=475",
            "category": "arcade",
            "rating": 4.9,
            "playCount": 3373,
            "releaseDate": "2025-04-15",
            "iframeUrl": "https://www.crazygames.com/embed/bicycle-kick-champ"
          }
    ]
};